import Head from 'next/head'
import styles from '../styles/Home.module.css'
import {daysInYear} from 'date-fns'

export default function Test({someData = 'no data'}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Test Page: Number of days in the year is {daysInYear}
        </h1>
        <p>Some data: {someData}</p>
      </main>
    </div>
  )
}

export async function getStaticProps(context) {
  let someData = null

  if (context?.previewData) {
    someData = context.previewData.someData
  }

  return {
    props: {
      someData
    },
  }
}